### ISSUE TITLE
o,no

### ISSUE THREAD

**Issue by mike-2333** [Tiaiceg/WebUIforLmStudio#2]
![1](https://github.com/user-attachments/assets/b6250f35-d655-4e9d-9593-53a08a3e3f12)

**Comment by Tiaiceg** [comment]
图片似乎没有上传,请检查😭

**Comment by Tiaiceg** [comment]
![image](https://github.com/user-attachments/assets/9ae6a415-5b35-4bfe-93cb-55eea49fe6fc)
如图请等待上传完毕再进行评论,
![image](https://github.com/user-attachments/assets/ad1fb3ed-7a0f-4b83-bf2c-2dcba152fad1)

**Comment by Tiaiceg** [comment]
请确认你的Pillow库是否正常?

卸载
```bash
pip uninstall pillow
```
然后重新安装
```bash
pip install pillow
```

**Comment by mike-2333** [comment]
那个什么pillow在哪。

**Comment by Tiaiceg** [comment]
当前来看,安装目录应该位于D:\Word\python\Lib\site-packages\PIL
但是应该没有必要查看安装文件,执行我上一条评论的指令进行卸载和重装即可

**Comment by mike-2333** [comment]
报错如下：
Traceback (most recent call last):
  File "D:\Word\python\Lib\threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "D:\Word\python\Lib\threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Word\python\Lib\site-packages\gradio\analytics.py", line 70, in _do_normal_analytics_request
    data["ip_address"] = get_local_ip_address()
                         ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Word\python\Lib\site-packages\gradio\analytics.py", line 131, in get_local_ip_address
    ip_address = httpx.get(
                 ^^^^^^^^^^
  File "D:\Word\python\Lib\site-packages\httpx\_api.py", line 198, in get
    return request(
           ^^^^^^^^
  File "D:\Word\python\Lib\site-packages\httpx\_api.py", line 106, in request
    return client.request(
           ^^^^^^^^^^^^^^^
  File "D:\Word\python\Lib\site-packages\httpx\_client.py", line 827, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Word\python\Lib\site-packages\httpx\_client.py", line 914, in send
    response = self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Word\python\Lib\site-packages\httpx\_client.py", line 942, in _send_handling_auth
    response = self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Word\python\Lib\site-packages\httpx\_client.py", line 979, in _send_handling_redirects
    response = self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Word\python\Lib\site-packages\httpx\_client.py", line 1015, in _send_single_request
    response = transport.handle_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Word\python\Lib\site-packages\httpx\_transports\default.py", line 232, in handle_request
    with map_httpcore_exceptions():
  File "D:\Word\python\Lib\contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "D:\Word\python\Lib\site-packages\httpx\_transports\default.py", line 86, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectTimeout: _ssl.c:983: The handshake operation timed out

**Comment by Tiaiceg** [comment]
疑似是未开启LmStudio导致的错误,开启LmStudio后重试

**Comment by mike-2333** [comment]
gui正常启动，依旧handshake错误

**Comment by Tiaiceg** [comment]
测试gui能否正常使用

**Comment by mike-2333** [comment]
handshake问题已解决，是因为系统防火墙阻止了程序通信，但报错仍在继续：
Traceback (most recent call last):
  File "D:\Word\python\Lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Word\python\Lib\site-packages\gradio\route_utils.py", line 275, in call_process_api
    with utils.MatplotlibBackendMananger():
  File "D:\Word\python\Lib\site-packages\gradio\utils.py", line 1008, in __enter__
    import matplotlib
  File "D:\Word\python\Lib\site-packages\matplotlib\__init__.py", line 109, in <module>
    from . import _api, _version, cbook, docstring, rcsetup
  File "D:\Word\python\Lib\site-packages\matplotlib\cbook\__init__.py", line 31, in <module>
    from matplotlib import _api, _c_internal_utils
ImportError: cannot import name '_c_internal_utils' from partially initialized module 'matplotlib' (most likely due to a circular import) (D:\Word\python\Lib\site-packages\matplotlib\__init__.py)

**Comment by Tiaiceg** [comment]
建议更新库文件,检查python update的输出
```bash
pip install --upgrade gradio matplotlib
```
并安装如下的库:
```bash
pip install gradio flask matplotlib pillow
```

**Comment by mike-2333** [comment]
这个项目还会继续更新吗，目前依然没法使用
